application: the-schedule
version: beta
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /telegram/.* 
  script: service.telegram.app
  secure: optional
- url: /admin/.*
  script: google.appengine.ext.admin.application #админка
  login: admin
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /style\.css
  static_files: templates/style.css
  upload: templates/style.css
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
