application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url:/back\.jpg
  static_files: /templates/back.jpg
  upload: /templates/back.jpg
- url: /style\.css
  static_files: templates/style.css
  upload: /templates/style.css
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest